services:
  db:
    image: postgres
    container_name: mytravel-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=my_travel
      - POSTGRES_PASSWORD=travel
      - POSTGRES_DB=mytravel_db
    volumes:
      - ../database_storage:/var/lib/postgresql

  mailpit:
    image: axllent/mailpit:latest
    container_name: mytravel-mailpit
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
